Parameters:
  GithubOidc:
    Type: String

Resources:
  GithubRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: codeguru42/docker-example:*
      Path: /docker_example/
      Policies:
        - PolicyName: EcrPolicy
          PolicyDocument: {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": Allow,
                "Action": [
                  ecr:GetAuthorizationToken,
                  ecr:BatchGetImage,
                  ecr:BatchCheckLayerAvailability,
                  ecr:CompleteLayerUpload,
                  ecr:GetDownloadUrlForLayer,
                  ecr:InitiateLayerUpload,
                  ecr:PutImage,
                  ecr:UploadLayerPart,
                ],
                "Resource": "*"
              },
            ]
          }

Outputs:
  Role:
    Value: !GetAtt GithubRole.Arn
